import type { GridFormatMessage, GridLabels } from '../types';

export const defaultGridLabels: GridLabels = {
  active: 'Active',
  activeRow: 'Active row',
  addFilterFor: 'Add filter for {label}',
  addPresentationRule: 'Add rule',
  addRowToSelection: 'Add row to selection',
  aggregateColumn: 'Aggregate column',
  aggregationScopeAll: 'All pages',
  aggregationScopePage: 'Current page',
  autoFitAllColumns: 'Auto fit all columns',
  autoFitThisColumn: 'Auto fit this column',
  autoLabel: 'Auto',
  autoPageSize: 'Auto page size',
  background: 'Background',
  booleanIcon: 'Boolean icon',
  cancel: 'Cancel',
  cell: 'Cell',
  checkMark: 'Check mark',
  checkMarkDisplay: 'Check mark',
  clear: 'Clear',
  clearAllFilters: 'Clear all filters',
  clearSort: 'Clear sort',
  close: 'Close',
  closeFilterMenu: 'Close filter menu',
  coloredDot: 'Colored dot',
  compactPill: 'Compact pill',
  condition: 'Condition',
  columnApiFallback: 'Column API fallback',
  columnFilters: 'Column filters',
  columnLayout: 'Column layout',
  columnSettings: 'Column settings',
  columnSettingsDescription: 'Choose visibility, order, and fixed widths for the TanStack columns. Settings persist in local storage for this preview.',
  columnTitlePrefix: 'Column',
  compact: 'Compact',
  copyCellValue: 'Copy cell value',
  copyRowValues: 'Copy row values',
  count: 'Count',
  crossMark: 'Cross mark',
  crossMarkDisplay: 'Cross mark',
  comfortable: 'Comfortable',
  deleteRule: 'Delete {name}',
  density: 'Density',
  display: 'Display',
  done: 'Done',
  dragColumn: 'Drag column',
  dragNamedColumn: 'Drag {label}',
  dragNamedRule: 'Drag {name}',
  dragRule: 'Drag rule',
  editPresentation: 'Presentation settings',
  editFilterFor: 'Edit filter for {label}',
  emptyCellValue: 'Empty',
  emptyState: 'No rows match the current search and filters.',
  exportExcel: 'Export to Excel',
  exportPdf: 'Export PDF',
  field: 'Field',
  filterByThisValue: 'Filter by this value',
  filterValue: 'Filter value',
  firstPage: 'First page',
  gridFailedToRender: 'The grid failed to render.',
  header: 'Header',
  headerRuleSummary: '{target} for {field}',
  hideColumn: 'Hide column',
  hideFilters: 'Hide filters',
  hideSummary: 'Hide summary',
  keepValue: 'Keep value',
  lastDoubleClick: 'Last double-click',
  lastPage: 'Last page',
  loadingColumns: 'Loading columns...',
  loadingTable: 'Loading table...',
  matchingRows: 'Matching rows',
  moveLeft: 'Move left',
  moveRight: 'Move right',
  nextPage: 'Next page',
  none: 'none',
  noPresentationRules: 'No presentation rules configured.',
  noAggregatableColumns: 'No columns available for summaries',
  noValuesFound: 'No values found',
  off: 'off',
  ok: 'OK',
  operator: 'Operator',
  openColumnSettings: 'Open column settings',
  paging: 'Paging',
  preset: 'Preset',
  presentationEditorInfo: 'Rules run from top to bottom. Drag cards to change which matching rule wins first.',
  presentationRules: 'Presentation rules',
  previousPage: 'Previous page',
  preview: 'Preview',
  print: 'Print',
  printThisRow: 'Print this row',
  removeFromSelection: 'Remove from selection',
  renderingFallbackColumns: 'Rendering fallback columns.',
  resetDefaults: 'Reset defaults',
  resetColumnLayout: 'Reset column layout',
  restoreDefaults: 'Restore defaults',
  row: 'Row',
  rowActions: 'Row actions',
  ruleName: 'Rule name {id}',
  ruleSummary: '{target} when {field} {operator}{value}',
  rows: 'Rows',
  rowsSuffix: 'rows',
  save: 'Save',
  search: 'Search',
  searchPlaceholder: 'Search',
  searchValues: 'Search {label} values',
  selectRow: 'Select row',
  selectAll: 'Select all',
  selectedRows: 'Selected rows',
  selectionCallback: 'Selection callback',
  setAsCustom: 'Set custom',
  setAsActiveRow: 'Set as active row',
  showingAllRows: 'Showing all {total} {rows}',
  showFilters: 'Show filters',
  showSummary: 'Show summary',
  scope: 'Scope',
  summary: 'Summaries',
  summaryDetails: 'Summary details',
  sortAtoZ: 'Sort A to Z',
  sortAscending: 'Sort ascending',
  sortDescending: 'Sort descending',
  sortZtoA: 'Sort Z to A',
  standard: 'Standard',
  style: 'Style',
  syncRenderedWidths: 'Sync rendered widths',
  tanStackTableError: 'TanStack table error',
  target: 'Target',
  text: 'Text',
  trueValue: 'True',
  falseValue: 'False',
  value: 'Value',
  visibleRows: 'Visible rows',
  when: 'When',
  width: 'Width',
  average: 'Average',
  contains: 'Contains',
  doesNotContain: 'Does not contain',
  equals: 'Equals',
  greaterThan: 'Greater than',
  isEmpty: 'Is empty',
  isNotEmpty: 'Is not empty',
  max: 'Max',
  min: 'Min',
  notEquals: 'Does not equal',
  startsWith: 'Starts with',
  endsWith: 'Ends with',
  sum: 'Sum',
  accent: 'Accent',
  info: 'Info',
  muted: 'Muted',
  success: 'Success',
  warning: 'Warning',
};

export const enUS: GridLabels = defaultGridLabels;

export const plPL: GridLabels = {
  ...defaultGridLabels,
  active: 'Aktywne',
  activeRow: 'Aktywny wiersz',
  addFilterFor: 'Dodaj filtr dla {label}',
  addPresentationRule: 'Dodaj regułę',
  addRowToSelection: 'Dodaj wiersz do zaznaczenia',
  aggregateColumn: 'Kolumna agregacji',
  aggregationScopeAll: 'Wszystkie',
  aggregationScopePage: 'Strona',
  autoFitAllColumns: 'Dopasuj wszystkie kolumny',
  autoFitThisColumn: 'Dopasuj tę kolumnę',
  autoLabel: 'Auto',
  autoPageSize: 'Automatyczny rozmiar strony',
  background: 'Tło',
  cancel: 'Anuluj',
  cell: 'Komórka',
  checkMark: 'Znacznik wyboru',
  checkMarkDisplay: 'Znacznik wyboru',
  clear: 'Wyczyść',
  clearAllFilters: 'Wyczyść wszystkie filtry',
  clearSort: 'Wyczyść sortowanie',
  close: 'Zamknij',
  closeFilterMenu: 'Zamknij menu filtra',
  coloredDot: 'Kolorowa kropka',
  compact: 'Kompaktowy',
  compactPill: 'Kompaktowa etykieta',
  condition: 'Warunek',
  columnApiFallback: 'Awaryjne kolumny',
  columnFilters: 'Filtry kolumn',
  columnLayout: 'Układ kolumn',
  columnSettings: 'Ustawienia kolumn',
  columnSettingsDescription: 'Wybierz widoczność, kolejność i szerokości kolumn.',
  columnTitlePrefix: 'Kolumna',
  comfortable: 'Wygodny',
  contains: 'Zawiera',
  copyCellValue: 'Kopiuj wartość komórki',
  copyRowValues: 'Kopiuj wartości wiersza',
  count: 'Liczba',
  crossMark: 'Krzyżyk',
  crossMarkDisplay: 'Krzyżyk',
  deleteRule: 'Usuń {name}',
  density: 'Gęstość',
  display: 'Wyświetlanie',
  doesNotContain: 'Nie zawiera',
  done: 'Gotowe',
  dragColumn: 'Przeciągnij kolumnę',
  dragNamedColumn: 'Przeciągnij {label}',
  dragNamedRule: 'Przeciągnij {name}',
  dragRule: 'Przeciągnij regułę',
  editFilterFor: 'Edytuj filtr dla {label}',
  editPresentation: 'Ustawienia prezentacji',
  emptyCellValue: 'Puste',
  emptyState: 'Brak wierszy pasujących do wyszukiwania i filtrów.',
  endsWith: 'Kończy się na',
  equals: 'Równa się',
  exportExcel: 'Eksportuj do Excela',
  exportPdf: 'Eksportuj PDF',
  falseValue: 'Fałsz',
  field: 'Pole',
  filterByThisValue: 'Filtruj po tej wartości',
  filterValue: 'Wartość filtra',
  gridFailedToRender: 'Nie udało się wyrenderować grida.',
  greaterThan: 'Większe niż',
  header: 'Nagłówek',
  headerRuleSummary: '{target} dla {field}',
  hideFilters: 'Ukryj filtry',
  hideSummary: 'Ukryj podsumowanie',
  info: 'Informacja',
  isEmpty: 'Jest puste',
  isNotEmpty: 'Nie jest puste',
  keepValue: 'Zachowaj wartość',
  lastDoubleClick: 'Ostatnie podwójne kliknięcie',
  loadingColumns: 'Ładowanie kolumn...',
  loadingTable: 'Ładowanie tabeli...',
  matchingRows: 'Pasujące wiersze',
  muted: 'Stonowany',
  noPresentationRules: 'Brak skonfigurowanych reguł prezentacji.',
  noAggregatableColumns: 'Brak kolumn do podsumowania',
  noValuesFound: 'Nie znaleziono wartości',
  none: 'brak',
  notEquals: 'Nie równa się',
  off: 'wyłączone',
  ok: 'OK',
  operator: 'Operator',
  preset: 'Preset',
  presentationEditorInfo: 'Reguły działają od góry do dołu. Przeciągaj karty, aby zmienić priorytet.',
  presentationRules: 'Reguły prezentacji',
  preview: 'Podgląd',
  print: 'Drukuj',
  renderingFallbackColumns: 'Renderowanie kolumn awaryjnych.',
  resetDefaults: 'Przywróć domyślne',
  restoreDefaults: 'Przywróć domyślne',
  row: 'Wiersz',
  rows: 'Wiersze',
  rowsSuffix: 'wierszy',
  ruleName: 'Nazwa reguły {id}',
  ruleSummary: '{target}, gdy {field} {operator}{value}',
  save: 'Zapisz',
  search: 'Szukaj',
  searchPlaceholder: 'Szukaj',
  searchValues: 'Szukaj wartości: {label}',
  selectAll: 'Zaznacz wszystko',
  selectedRows: 'Zaznaczone wiersze',
  selectionCallback: 'Callback zaznaczenia',
  setAsCustom: 'Ustaw własny',
  showingAllRows: 'Wyświetlanie wszystkich: {total} {rows}',
  showFilters: 'Pokaż filtry',
  showSummary: 'Pokaż podsumowanie',
  scope: 'Zakres',
  summary: 'Podsumowania',
  summaryDetails: 'Szczegóły',
  sortAtoZ: 'Sortuj A do Z',
  sortAscending: 'Sortuj rosnąco',
  sortDescending: 'Sortuj malejąco',
  sortZtoA: 'Sortuj Z do A',
  standard: 'Standardowy',
  startsWith: 'Zaczyna się od',
  style: 'Styl',
  success: 'Sukces',
  sum: 'Suma',
  tanStackTableError: 'Błąd tabeli TanStack',
  target: 'Cel',
  text: 'Tekst',
  trueValue: 'Prawda',
  value: 'Wartość',
  visibleRows: 'Widoczne wiersze',
  warning: 'Ostrzeżenie',
  when: 'Kiedy',
  width: 'Szerokość',
};

function interpolate(message: string, values?: Record<string, unknown>) {
  if (!values) {
    return message;
  }

  return Object.entries(values).reduce(
    (currentMessage, [key, value]) => currentMessage.replaceAll(`{${key}}`, String(value ?? '')),
    message,
  );
}

export function createGridMessageResolver({
  formatMessage,
  labels,
}: {
  formatMessage?: GridFormatMessage;
  labels?: Partial<GridLabels> & Record<string, string>;
} = {}) {
  return (key: keyof GridLabels | string, fallback?: string, values?: Record<string, unknown>) => {
    const defaultMessage = String(labels?.[key] ?? defaultGridLabels[key] ?? fallback ?? key);

    if (typeof formatMessage === 'function') {
      return formatMessage(
        {
          defaultMessage,
          id: `tanstackGrid.${key}`,
        },
        values,
      );
    }

    return interpolate(defaultMessage, values);
  };
}
