export const demoRows = [
  {
    id: 'CMP-1024',
    owner: 'Ava Simmons',
    region: 'North America',
    status: 'Live',
    revenue: '$128,400',
    updatedAt: '2h ago',
  },
  {
    id: 'CMP-1048',
    owner: 'Luca Moreno',
    region: 'EMEA',
    status: 'Review',
    revenue: '$92,170',
    updatedAt: '5h ago',
  },
  {
    id: 'CMP-1081',
    owner: 'Mina Cho',
    region: 'APAC',
    status: 'Draft',
    revenue: '$61,090',
    updatedAt: 'Today',
  },
  {
    id: 'CMP-1097',
    owner: 'Jonah Patel',
    region: 'LATAM',
    status: 'Live',
    revenue: '$149,600',
    updatedAt: 'Yesterday',
  },
  {
    id: 'CMP-1122',
    owner: 'Nora Faye',
    region: 'North America',
    status: 'Review',
    revenue: '$84,300',
    updatedAt: '1d ago',
  },
  {
    id: 'CMP-1139',
    owner: 'Elias Reed',
    region: 'EMEA',
    status: 'Live',
    revenue: '$171,210',
    updatedAt: '3d ago',
  },
  {
    id: 'CMP-1164',
    owner: 'Sofia Bennett',
    region: 'APAC',
    status: 'Draft',
    revenue: '$47,990',
    updatedAt: '4d ago',
  },
  {
    id: 'CMP-1175',
    owner: 'Marek Silva',
    region: 'North America',
    status: 'Review',
    revenue: '$103,800',
    updatedAt: '1w ago',
  },
];
